import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://folcademy.com/home">Hola mundo!</a>
        </h1>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Est ducimus, vero dignissimos molestiae doloribus sunt qui expedita, quasi ipsa temporibus dolor repellendus accusamus, a ab magnam nam tempora pariatur reprehenderit voluptates deleniti atque eius! Ipsa suscipit repellendus consequatur quod, ipsam expedita facilis in provident alias? Veniam repellendus quasi voluptatum. Beatae!          
        </p>        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Fernando Icazatti - Curso React - {' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
